{ pkgs, lib, ... }:
lib.mkMerge [
  (import ./auto-pairs.nix)
  (import ./autocmds.nix { inherit pkgs; })
  (import ./cmp.nix { inherit lib; })
  (import ./git.nix)
  (import ./custom-plugins.nix { inherit pkgs; })
  (import ./keymaps.nix)
  (import ./lsp.nix { inherit pkgs; })
  (import ./languages.nix { inherit pkgs; })
  (import ./formatter.nix { inherit pkgs; })
  (import ./mini.nix)
  (import ./options.nix)
  (import ./settings.nix { inherit pkgs; })
  (import ./snippets.nix)
  (import ./telescope.nix { inherit pkgs; })
  (import ./theme.nix)
  (import ./todo.nix)
  (import ./which-key.nix { inherit pkgs; })
  (import ./noice.nix)
  (import ./notify.nix)
  (import ./oil.nix)
]
